name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        Class MainA
{
Public static void main()
{
pringf("Hello find below add function");
a.Add();
}
Class A
{
A a = new A();
void Add()
{
int ad = 10+2;
printf("addition:"+ad);
}
}
}
